#!/bin/bash
set -e -u


# checking if I have the latest files from github
echo "Checking for newer files online first"
git pull

# Below command will backup everything inside the project folder
git add --all .

# Give a comment to the commit if you want
echo "####################################"
echo "Write your commit comment!"
echo "####################################"

read input

if [ -z $input ]
then
  input="cambio menor"
fi

echo $input
git commit -m "$input"

# Push the local files to github

git push

echo "################################################################"
echo "###################    Git Push Done      ######################"
echo "################################################################"
